### ISSUE TITLE
This plugin doesn't seem to use logical properties and values

### ISSUE THREAD

**Issue by bboro** [thibaudcolas/tailwindcss-vanilla-rtl#10]
### Describe the bug

Installed the plugin and re-compiled my theme. 

In the compiled CSS file there are no logical properties or values to be found. However I can now see that the plugin simply adds `[dir=ltr]` (or `[dir=rtl]`) in front of classes such as `ml`/`mr` etc:

```css
[dir=ltr] .ml-2{margin-left:.5rem}
[dir=rtl] .ml-2{margin-right:.5rem}
```

According to the plugin readme, shouldn't this instead just be:

```css
.ml-2 { margin-inline-start: .5rem}
```

### Which terms did you search for in the documentation and issue tracker?

(Write your answer here if relevant.)

### Environment

- Tailwind 3.1.8
